function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 08-Apr-2014 11:09:49

% Create figure
figure1 = figure('NumberTitle','off','Name','My First plot');

% Create axes
axes1 = axes('Parent',figure1,'YScale','log','YMinorTick','on');
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to semilogy
semilogy1 = semilogy(X1,YMatrix1);
set(semilogy1(1),'LineStyle',':','Color',[0 0 1]);
set(semilogy1(2),'MarkerFaceColor',[1 1 1],'MarkerSize',15,...
    'Marker','square',...
    'LineWidth',2,...
    'Color',[0 0.498039215803146 0]);

% Create xlabel
xlabel('Time (s)');

% Create ylabel
ylabel('Signal (units)');

