function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'psychometric fit' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 24-Apr-2019 14:00:55


%% Fit: 'psychometric fit'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( '1/(1 + exp(-(x-a)/b))', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0];
opts.StartPoint = [0.485375648722841 0.8002804688888];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'psychometric fit' );
h = plot( fitresult, xData, yData, 'predobs' );
legend( h, 'y vs. x', 'psychometric fit', 'Lower bounds (psychometric fit)', 'Upper bounds (psychometric fit)', 'Location', 'NorthEast' );
% Label axes
xlabel x
ylabel y
grid on


