function createfigure1(X1, Y1)
%CREATEFIGURE1(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 14-Jun-2017 14:33:52

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1,'MarkerFaceColor',[1 1 1],'MarkerSize',10,'Marker','o',...
    'LineWidth',2,...
    'Color',[1 0 0]);

box(axes1,'on');
