function [fitresult, gof] = fitPsychometric(x, y)
    % fitPsychometric(X,Y) - fit x/y data from psychometric experiments
    %  Create a fit.
    %
    %  Data for 'psychometric fit' fit:
    %      X Input: x
    %      Y Output: y
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    %
    % generated by DS during the matlab course 2022-04-21

    %  Auto-generated by MATLAB on 21-Apr-2022 10:12:25


    %% Fit: 'psychometric fit'.
    [xData, yData] = prepareCurveData( x, y );

    % Set up fittype and options.
    ft = fittype( '1/(1+exp(-(x/a))/b)', 'independent', 'x', 'dependent', 'y' );
    opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
    opts.Display = 'Off';
    opts.StartPoint = [0.894882940676557 0.444706251048628];

    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, opts );

    % Plot fit with data.
    figure( 'Name', 'psychometric fit' );
    h = plot( fitresult, xData, yData );
    legend( h, 'y vs. x', 'psychometric fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 'x', 'Interpreter', 'none' );
    ylabel( 'y', 'Interpreter', 'none' );
    grid on


