%% load and plot some data
%
%
%  it contains some typical psychometric curve data from an actual
%  experiment. We are using a chunk of the whole file t

% let's use importdata with this file
filename =  'psycho-test-01.txt';
d = importdata(filename)

%% make a plot

% first column of the table/matrix contains x values
x = d(:,1)

% second column contains y-values
y = d(:,2)

figure
plot(x,y, 'ro-')

%% now use autogenerated code


createFit(x,y)


%% Notes
%  the original file was downloaded from: 
% 
url = 'https://raw.githubusercontent.com/schluppeck/zamboni-2016/master/subjectA-discrimination.csv';

% what does this look like in web browser?
web(url)

%% help with CSV type data
options = weboptions('ContentReader', @importdata);

% go straight to this website and grab data...
d = webread(url, options)
